### ISSUE TITLE
autodetect services

### ISSUE THREAD

**Issue by RaphaelAudet** [mendix/IBM-Watson-Connector-Suite#4]
- [x] only autodetect once
- [x] conversation
- [x] language_translator 
- [x] tone_analyzer

**Comment by RaphaelAudet** [comment]
- [x] conversation service needs GUID

**Comment by RaphaelAudet** [comment]
conversation errors 

```
 ERR Jan 24, 2017 9:49:47 AM com.ibm.watson.developer_cloud.service.WatsonService processServiceCall
2017-01-24T10:49:47.41+0100 [APP/0]      OUT ERROR - IBM Watson Connector - Conversation: Watson Service connection - Failed conversing with Watson in the workspaceID 76eb2099-94b6-49c6-9cc5-1c219f110dce
2017-01-24T10:49:47.41+0100 [APP/0]      ERR SEVERE: POST https://gateway.watsonplatform.net/conversation/api/v1/workspaces/76eb2099-94b6-49c6-9cc5-1c219f110dce/message?version=2016-07-11, status: 404, error: Resource not found
2017-01-24T10:49:47.41+0100 [APP/0]      OUT 	at com.ibm.watson.developer_cloud.service.WatsonService.processServiceCall(WatsonService.java:422)
2017-01-24T10:49:47.41+0100 [APP/0]      OUT 	at com.ibm.watson.developer_cloud.service.WatsonService$1.execute(WatsonService.java:179)
2017-01-24T10:49:47.41+0100 [APP/0]      OUT 	at watsonservices.actions.SendMessage.executeAction(SendMessage.java:43)
2017-01-24T10:49:47.41+0100 [APP/0]      OUT 	at watsonservices.actions.SendMessage.executeAction(SendMessage.java:20)
```

**Comment by RaphaelAudet** [comment]
translation service logs

```
  ERR Jan 24, 2017 9:54:34 AM com.ibm.watson.developer_cloud.service.WatsonService processServiceCall
2017-01-24T10:54:34.31+0100 [APP/0]      ERR SEVERE: GET https://gateway.watsonplatform.net/language-translation/api/v2/identifiable_languages, status: 401, error: Not Authorized
2017-01-24T10:54:34.31+0100 [APP/0]      OUT ERROR - IBM Watson Connector - Translate: Watson Service Connection - Failed retrieving the identifiable languages
2017-01-24T10:54:34.31+0100 [APP/0]      OUT ERROR - IBM Watson Connector - Translate: com.ibm.watson.developer_cloud.service.exception.UnauthorizedException: Unauthorized: Access is denied due to invalid credentials
2017-01-24T10:54:34.31+0100 [APP/0]      OUT 	at com.ibm.watson.developer_cloud.service.WatsonService.processServiceCall(WatsonService.java:418)
2017-01-24T10:54:34.31+0100 [APP/0]      OUT 	at com.ibm.watson.developer_cloud.service.WatsonService$1.execute(WatsonService.java:179)
2017-01-24T10:54:34.31+0100 [APP/0]      OUT 	at watsonservices.utils.LanguageTranslationService.getIdentifiableLanguages(LanguageTranslationService.java:34)
2017-01-24T10:54:34.31+0100 [APP/0]      OUT 	at watsonservices.actions.GetIdentifiableLanguages.executeAction(GetIdentifiableLanguages.java:33)
2017-01-24T10:54:34.31+0100 [APP/0]      OUT 	at watsonservices.actions.GetIdentifiableLanguages.executeAction(GetIdentifiableLanguages.java:17)
```

**Comment by RaphaelAudet** [comment]
- [x] remove  credentials in logs

**Comment by RaphaelAudet** [comment]
- [x] json mapping
